name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.10','3.11','3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Compile
        run: |
          mkdir build
          uv run python tools/compile.py

      - name: Test
        run: |
          uv run pytest -s -vvvv

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Create automatic release
        if: matrix.python-version == '3.11'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: nightly
          title: Nightly Build ${{ steps.date.outputs.date }}
          files: |
            build/ref-schema.ttl

